---
title: panic
---

Rust 的处理处理分为两类：

- 可恢复的错误
  - 文件未找到 可以再次尝试查询
- 不可恢复的错误
  - bug 数组边界越界等情况

Rust 没有类似异常的机制 但有 Api 和宏来处理异常

对于可恢复的错误 一般使用`Result<T,E>` Api 去解决，对于不可恢复的错误 则会调用`panic!`宏去输出错误日志。

## panic! 产生错误信息

`panic!` 可能出现我们编写的代码或者所依赖的代码中。通过`panic`的错误信息可以用来定位问题代码的位置。

当`panic`发生时，有以下两种情况：

- 程序展开调用站

  - Rust 沿着调用栈往回走
  - 清理每个遇到的函数中的数据

- 立即终止调用栈

  - 不进行数据清理，直接停止程序
  - 内存需要`OS` 进行清理

  > 设置由**展开** 变为**中止** 改变`Cargo.toml`
  >
  > ```rust
  > [profile.release]
  > panic = 'abort' // 终止调用栈
  > ```

> 通过设置环境变量`RUST_BACKTRACE` 可以得到回溯信息。 如果需要获取带有调试信息的回溯（不要在`cargo run/build` 的时候 带上`--release`）
